# Use the official Go image as the base image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the code into the container
COPY . .

# Install any dependencies
RUN go mod init ipchecker

# Install any dependencies
RUN go get github.com/lib/pq

# Build the code
RUN go build -o main .

# Expose the port on which the application is running
EXPOSE 8080


# Run the application
CMD ["./main"]
